async function iPromiseYouAError () {
	throw new Error('Esto no aparecer치 como un Error sino como una promesa rechazada')
	// return Promise.reject('Esto no aparecer치 como un Error sino como una promesa rechazada')
	// return Promise.reject(new Error('Esto no aparecer치 como un Error sino como una promesa rechazada'))
}

iPromiseYouAError().catch((err) => {
	console.log('catched:', err.message)
}) // catched: Esto no aparecer치 como un error lanzado sino como una promesa rechazada
